### ISSUE TITLE
resolveConflict() does not apply changes

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/lix-sdk#62] opened 2024-08-28 16:41 UTC
### Context

* "Keep" applies on refresh
* "Accept" resolves, but does not apply the change

File to reproduce:

[niklas-samuel-conflict.inlang](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a85b9ede-3db1-4431-b519-9b11aadbf0b1/cd01fbee-94c2-4d3d-af7f-e740d9cead51?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hODViOWVkZS0zZGIxLTQ0MzEtYjUxOS05YjExYWFkYmYwYjEvY2QwMWZiZWUtOTRjMi00ZDNkLWFmN2YtZTc0MGQ5Y2VhZDUxIiwiaWF0IjoxNzI0ODYzMzE4LCJleHAiOjMzMjk1NDIzMzE4fQ.bwRqK43mVctLOaF4zxyG0Z0ynH_S2UmcwAhCU77_zME)

**Comment by samuelstroschein** [comment] 2024-08-28 20:04
## Keep bug

"keep" has been fixed in [https://github.com/opral/monorepo/commit/65f7b4a8c56fc92d68db89263e93cc760fd8f5f2](https://github.com/opral/monorepo/commit/65f7b4a8c56fc92d68db89263e93cc760fd8f5f2). 

the bug was caused by buggy polling with `useEffect` (classic react). 

see as i progressed finding the bug in the loom [https://www.loom.com/share/1527d570ba1847f5a9108498b3d6edeb?sid=bb37954f-e62f-4437-bf56-4e392b5994b3](https://www.loom.com/share/1527d570ba1847f5a9108498b3d6edeb?sid=bb37954f-e62f-4437-bf56-4e392b5994b3)

working on bug 2 now

**Comment by samuelstroschein** [comment] 2024-08-29 03:00
Uff bug 2 is a big one. I was able to replicate it. Added test. Works now. Except that the window needs to be refreshed. 

I will add a follow issue for that.

**Comment by samuelstroschein** [comment] 2024-08-29 03:04
[LIX-141](https://linear.app/opral/issue/LIX-141/fix-refresh-after-resolving-conflicts) prio is low. given that i want to complete [inlang SDK V2 (sqlite)](https://linear.app/opral/project/inlang-sdk-v2-sqlite-3f2d774383dd).

**Closed by samuelstroschein** 2024-08-29 03:04 UTC
Labels: bug
